#ifndef _SBS_ERROR_H_
#define _SBS_ERROR_H_

#define SBS_SUCCESS 0
#define SBS_GENERAL_ERROR -1
#define SBS_ERROR_INVALID_PARAM -2
#define SBS_ERROR_READ_FILE_FAILED -3
#define SBS_ERROR_JSON_PARSE_FAILED -4
#define SBS_ERROR_GET_CWD_FAILED -5
#define SBS_ERROR_RTP_CFG_INVALID_MODE -6
#define SBS_ERROR_RTP_CFG_INVALID_PARAM -7
#define SBS_ERROR_ROOM_NOT_EXIST -8
#define SBS_ERROR_PEER_NOT_EXIST -9
#define SBS_ERROR_START_SBS_THREAD_FAILED -10

#endif//_SBS_ERROR_H_

